# Generated by Django 5.0.3 on 2024-03-09 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('img', models.CharField(max_length=10000)),
                ('discount', models.FloatField()),
                ('rating', models.FloatField()),
                ('link', models.CharField(max_length=10000)),
                ('reviews', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Filters',
        ),
        migrations.AddField(
            model_name='comparison',
            name='product1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product1_comparisons', to='api.product'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='product2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product2_comparisons', to='api.product'),
        ),
    ]
