# Generated by Django 5.0.3 on 2024-03-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comparison_product_delete_filters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='product1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='product2',
            field=models.IntegerField(),
        ),
    ]
